########################################################################
# TravisCI configuration for GraphQLAPI/graphql-api-for-wp
#
# There are 1+3 jobs.
#
# 1. PHPUnit on PHP 7.4 required for development
# 2. PHPCS on PHP 7.4
# 3. PHPStan on PHP 7.4
# 4. Run Rector to generate the PHP 7.1-compatible code for production
#    then PHPStan on PHP 7.1
######################################################################## 

language: php
os:
  - linux
dist: xenial

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
  - 7.4

jobs:
  include:
    - name: "PHPCS"
      script:
        - vendor/bin/phpcs -n --standard=PSR2 src/
      after_script: skip
    - name: "PHPStan"
      script:
        - vendor/bin/phpstan analyse -c phpstan.neon.dist src/
      after_script: skip
    - name: "Downgraded code"
      script:
        - vendor/bin/rector process
        - phpenv local 7.1
        - php --version
        - vendor/bin/phpstan analyse -c phpstan.neon.dist src/
      after_script: skip

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - leo@getpop.org
    on_success: change
    on_failure: always
